export const

    WHATSAPP_VERSION = 'WHATSAPP_VERSION',
    
    REGISTER = 'REGISTER',

    LOGIN = 'LOGIN',
    VERIFY_AUTHENTICATION = 'VERIFY_AUTHENTICATION',


    GET_SUB_HEADERS = 'GET_SUB_HEADERS',


    GET_HOME_PAGE_PRODUCTS = 'GET_HOME_PAGE_PRODUCTS',


    GET_PRODUCTS_OF_THE_CATEGORIES_DEFAULT = 'GET_PRODUCTS_OF_THE_CATEGORIES_DEFAULT',


    GET_PRODUCT_BY_REFERENCE = 'GET_PRODUCT_BY_REFERENCE',


    GET_SEARCH_TERM = 'GET_SEARCH_TERM',


    SET_CART = 'SET_CART',
    GET_CART_PRODUCT = 'GET_CART_PRODUCT', GET_CART_VARIATION = 'GET_CART_VARIATION', GET_CART_FRETE = 'GET_CART_FRETE',
    UPDATE_CART_QUANTITY = 'UPDATE_CART_QUANTITY', UPDATE_CART_FRETE = 'UPDATE_CART_FRETE',
    REMOVE_CART_PRODUCT = 'REMOVE_CART_PRODUCT', CLEAN_CART_FRETE = 'CLEAN_CART_FRETE', CLEAN_CART = 'CLEAN_CART',


    CHECKOUT_SET_FORM = 'CHECKOUT_SET_FORM',
    CHECKOUT_CLEAN_FORM = 'CHECKOUT_CLEAN_FORM',
    CHECKOUT_SET_PAYMENT_METHOD = 'CHECKOUT_SET_PAYMENT_METHOD',
    CHECKOUT_GET_SESSIONID = 'CHECKOUT_GET_SESSIONID',
    CHECKOUT_SENDERHASH = 'CHECKOUT_SENDERHASH',
    CHECKOUT_CREATE_REQUESTS = 'CHECKOUT_CREATE_REQUESTS',
    CHECKOUT_PAY_REQUESTS = 'CHECKOUT_PAY_REQUESTS',

    GET_REQUESTS = 'GET_REQUESTS',
    GET_REQUEST = 'GET_REQUEST',
    CLEAN_REQUEST = 'CLEAN_REQUEST',
    CANCEL_REQUEST = 'CANCEL_REQUEST'