export const 
    LOGIN = `LOGIN`,


    GET_REQUESTS = `GET_REQUESTS`,
    GET_REQUEST = `GET_REQUEST`,
    REMOVE_REQUEST = `REMOVE_REQUEST`,
    CLEAR_REQUEST = `CLEAR_REQUEST`,
    POST_REQUEST_PAYMENTS_STATUS = `UPDATE_REQUEST_PAYMENTS_DELIVERIES_STATUS`,


    GET_USERS = `GET_USERS`,
    GET_USER = `GET_USER`,
    UPDATE_USER = `UPDATE_USER`,
    REMOVE_USER = `REMOVE_USER`,
    GET_USER_REQUESTS = `GET_USER_REQUESTS`,


    CREATE_CATEGORY = `CREATE_CATEGORY`, 
    GET_CATEGORIES = `GET_CATEGORIES`, 
    GET_CATEGORY = `GET_CATEGORY`, 
    UPDATE_CATEGORY = `UPDATE_CATEGORY`, 
    REMOVE_CATEGORY = `REMOVE_CATEGORY`,


    CREATE_PRODUCT = `CREATE_PRODUCT`,
    GET_PRODUCTS = `GET_PRODUCTS`, 
    GET_PRODUCT = `GET_PRODUCT`, 
    UPDATE_PRODUCT = `UPDATE_PRODUCT`, 
    REMOVE_PRODUCT = `REMOVE_PRODUCT`,
    UPDATE_IMAGES = `UPDATE_IMAGES`
